### ISSUE TITLE
License for project?

### ISSUE THREAD

**Issue by ivoanjo** [mame/optcarrot#15]
Hello there!

Thanks for optcarrot --- it's a really interesting codebase to explore and play with in trying to get Ruby to go faster.

I noticed that there seems to be no license attached to the project, and would like to suggest that one be added. I personally favour [LGPLv3+](https://choosealicense.com/licenses/lgpl-3.0/) but you may want to select an even less complex license, such as [MIT](https://choosealicense.com/licenses/mit/) or [Apache](https://choosealicense.com/licenses/apache-2.0/).

Thanks :pray: :+1:

**Comment by eregon** [comment]
@ivoanjo The .gemspec specifies MIT so I guess that's the license:
https://github.com/mame/optcarrot/blob/aee723e0099ddce69485f7a638b54920da8f8e50/optcarrot.gemspec#L15
@mame Could you confirm?
I think adding a `LICENSE` file in the repo would clarify.

See https://github.com/mame/optcarrot/blob/master/examples/source.yml for the license of the roms.

**Comment by mame** [comment]
MIT LICENSE added!  Thank you.
