### ISSUE TITLE
Code does not support MRI 1.8.7

### ISSUE THREAD

**Issue by Ichaelus** [mame/optcarrot#19]
The documentation [benchmark.md](https://github.com/mame/optcarrot/blob/master/doc/benchmark.md) and plots are suggesting, that this benchmark can be run on mri-1.8.7 (or JRuby in MRI 1.8.7 compatibility mode). 
I am, however, unable to run it without extensive modifications. Further details:
* The modern hash syntax `foo: :bar` must be backported to `:foo => :bar`
* The splat operator can only be used as the last argument, further: arguments can't have a dynamic length unless they are the last. There are many places in your codebase that do not support that restriction. ([Example](https://github.com/mame/optcarrot/blob/master/lib/optcarrot/cpu.rb#L1105))

All the best,
Michael

**Comment by mame** [comment]
Yes, I'm using a script to rewrite all Ruby programs so that they can run on Ruby 1.8 and Opal.  I've added a note about it into benchmark.md.

**Comment by Ichaelus** [comment]
Thanks for helping me out!
Badly the script makes use of a [faulty](https://github.com/lsegal/ripper18/issues/9) gem `ripper`, but I'm looking forward to get things running soon.

**Comment by mame** [comment]
The scripts in the `tools/` directory support only the recent MRI, so it may not work on MRI 1.8.
