### ISSUE TITLE
JRuby performance in benchmark results tells a partial story

### ISSUE THREAD

**Issue by headius** [mame/optcarrot#2]
I'm confused by some of the numbers I've seen for JRuby versus MRI in the benchmark results.

Your numbers show MRI 2.3 being the fastest in non-optimized mode with 23FPS. JRuby 1.7.24 is the fastest production-usable implementation at 19FPS. JRuby 9k (9.0.5.0) has lower perf than 1.7.24.

My own numbers confirm some parts of this and not others.
# Invokedynamic not used

First, JRuby (stock) versus Ruby 2.3.0:

```
jruby 1.7.24 (1.9.3p551) 2016-01-20 bd68d85 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_60-b27 +jit [darwin-x86_64]
fps: 13.333334275233959
checksum: 59662

ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]
fps: 16.10170636312445
checksum: 59662
```

So JRuby is a bit slower, matching your results. But this is without invokedynamic, normally turned off for JRuby due to longer startup/warmup time.

```
jruby 1.7.24 (1.9.3p551) 2016-01-20 bd68d85 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_60-b27 +indy +jit [darwin-x86_64]
fps: 16.100178451396733
checksum: 59662
```

This puts JRuby 1.7 at about the speed of MRI 2.3.0 on the normal version of this code.
# JRuby 9k

Your results show a perf degradation from 1.7.24 to 9.0.5, which we have confirmed and made a number of fixes for in JRuby 9.1.

Note we have still not yet made homogeneous case/when O(1).

```
jruby 9.0.5.0 (2.2.3) 2016-01-26 7bee00d Java HotSpot(TM) 64-Bit Server VM 25.60-b23 on 1.8.0_60-b27 +indy +jit [darwin-x86_64]
fps: 12.010045906189871
checksum: 59662

jruby 9.1.0.0-SNAPSHOT (2.3.0) 2016-03-24 d851678 Java HotSpot(TM) 64-Bit Server VM 25.60-b23 on 1.8.0_60-b27 +indy +jit [darwin-x86_64]
fps: 30.92613156164269
checksum: 59662
```

This puts JRuby 9.1 nearly 2x faster than MRI 2.3.0 on the normal code.

It's also interesting to note that 9.1 does not appear to require any of the compatibility stubs.
# Optimized code

I can confirm that JRuby does not like the optimized code, most likely because very large bodies of code usually do not JIT in JRuby, or if they do JIT to JVM bytecode the JVM itself may not do further optimization on them. However, I thought I'd try it in JRuby anyway.

```
jruby 9.1.0.0-SNAPSHOT (2.3.0) 2016-03-24 d851678 Java HotSpot(TM) 64-Bit Server VM 25.60-b23 on 1.8.0_60-b27 +indy +jit [darwin-x86_64]
fps: 1.649363068304025
checksum: 59662
```

This is a 20x performance reduction by using the same "optimized" code that speeds up MRI by almost 3x.

If I turn on JIT logging (-Xjit.logging) I can see it fails to compile two generated pieces of code for `PPU.run` and `CPU.run`:

```
...
2016-03-31T21:49:06.096-05:00: JITCompiler: done jitting: DMC Optcarrot::APU::DMC.sample at /Users/headius/projects/optcarrot/lib/optcarrot/apu.rb:770
2016-03-31T21:49:06.411-05:00: JITCompiler: Could not compile; passes run: []: <anon class> Optcarrot::PPU.run at (generated PPU core):0 because of: "Could not compile org.jruby.internal.runtime.methods.MixedModeIRMethod@6b72f764; instruction count 204813 exceeds threshold of 2000"
2016-03-31T21:49:07.168-05:00: JITCompiler: done jitting: <block> poke_2007_CLOSURE_1.poke_2007_CLOSURE_1 at /Users/headius/projects/optcarrot/lib/optcarrot/ppu.rb:481
2016-03-31T21:49:07.181-05:00: JITCompiler: done jitting: PPU Optcarrot::PPU.update_scroll_address_line at /Users/headius/projects/optcarrot/lib/optcarrot/ppu.rb:297
...
```

This is producing a method that requires 204813 instructions in our IR. Most of our IR instructions compile to many JVM bytecodes. Combine these facts with the JVM's method size limit of 64k _bytes_ of JVM bytecode...even if we tried to force JRuby to JIT this code, it would be far too large for the JVM to accept it without us breaking it into smaller pieces.

Our interpreter-only mode is only slightly slower than the JIT when running with --opt. For the moment, this optimization does not fit JRuby's model of execution.

**Comment by mame** [comment]
Thank you, interesting!  I'll try later.

**Comment by headius** [comment]
I forgot to say thank you for coming up with an interesting way to measure Ruby performance! I'll spend some time playing with this and see what we can improve. Obviously I'll try to get the case/when optimization in first :-)

**Comment by mame** [comment]
@headius I have updated jruby benchmark results with using `-Xcompile.invokedynamic=true`.  Now it matches MRI 2.3 in the default mode.

Also confirmed 9.1.0.0-SNAPSHOT.  It marks 35 fps on my machine, while MRI 2.3 marks 26 fps.  Great!  I like to add it to the list when it is officially released.

> Note we have still not yet made homogeneous case/when O(1).

I think the default mode now uses no big case statement.  So, parhaps, case/when O(1) optimization will have less effect for the default mode.

> For the moment, this optimization does not fit JRuby's model of execution.

`--opt` is just my playground to explore promising optimizations for MRI.  So, never mind.  I think a good Ruby implementation runs faster the default mode, without having to use a dirty hack such as manual method inlining.

**Comment by headius** [comment]
> --opt is just my playground to explore promising optimizations for MRI. So, never mind. I think a good Ruby implementation runs faster the default mode, without having to use a dirty hack such as manual method inlining.

It may be interesting to come up with a similar flag for JRuby that avoids using language structures that have unfortunate side effects. For example, in order to support String#[](regexp) we must prepare space for a `$~` slot that *might* be needed. This affects all calls to `#[]`, even when `$~` is *not* needed. A JRuby-specific workaround is to use `Array#at`, since no version of `#at` needs `$~`.

I'll have a look at the code and see if we can do anything to improve perf on JRuby and other impls.

**Comment by mame** [comment]
> This affects all calls to `#[]`, even when `$~` is not needed.

Heh.  MRI does not do that.  Is it difficult to allocate the slot on demand?

> A JRuby-specific workaround is to use Array#at, since no version of #at needs $~.

Hmm.  Unfortunately, it is not trivial to replace `Array#[]` with `#at` because this program highly uses polymorphism of `Method#[]` and `Array#[]`.

To implement memory-mapped I/O, this program represents a memory read as `mem[addr][addr]`.  If the address is a normal memory cell, `mem[addr]` returns an Array (raw memory) and then `mem[addr][addr]` returns a stored value.  If the address is memory-mapped I/O (a trigger of circuit events), `mem[addr]` returns a Method object and then `mem[addr][addr]` invokes the event.  So, it is difficult to replace `#[]` with `#at` systematically.  I may try later manually.

**Comment by headius** [comment]
> Heh. MRI does not do that. Is it difficult to allocate the slot on demand?

At the moment, there's nothing to really "allocate" but we have to bump a frame pointer on the way in and out of any method with `[]` because we can't see downstream calls at that point to know if it's `String#[](regexp)` or not. That in turn requires some deoptimization of other aspects (most obviously, we can't omit the frame logic).

It's a worthwhile thing for us to improve, however, so we are continuing to explore options.

**Comment by mame** [comment]
Congrats to the release of JRuby 9.1.0.0!  I'll update the benchmark result next week.
