### ISSUE TITLE
Problem in --print-video-checksum

### ISSUE THREAD

**Issue by sisshiki1969** [mame/optcarrot#32]
In my environment, it seems that --print-video-checksum option does not work.
```sh
❯ ruby bin/optcarrot -b --print-video-checksum examples/Lan_Master.nes
fps: 40.230421976713764
❯ ruby tools/run-benchmark.rb ruby30
+--------------+
| build ruby30 |
+--------------+
*** omitted ***
+----------------------------------+
| measure ruby30 / default (1 / 1) |
+----------------------------------+
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
fps: 39.59678157409444

FAILED.

❯
```

I think, in the code below which is modified in the latest commit, ".class" is not necessary.
--print-video-checksum (or tools/run-benchmark.rb) worked correctly after I deleted ".class".
How do you think about this?

https://github.com/mame/optcarrot/blob/5d3ca1177afc973c8e14c44c4aa0000341db58e9/lib/optcarrot/nes.rb#L70

**Comment by mame** [comment]
Indeed! Could you please create a PR?

**Comment by sisshiki1969** [comment]
Roger that!
#34
